---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: burndash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: burndash
    spec:
      containers:
      - name: burndash
        image: aelmendorf234/burndash:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        envFrom:
        - configMapRef:
            name: burn-app-config
        
  selector:
    matchLabels:
      app: burndash
---
apiVersion: v1
kind: Service
metadata:
  name: burndash
spec:
  loadBalancerIP: 172.20.4.203
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32206
  selector:
    app: burndash
