apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2thstream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e2thstream
    spec:
      containers:
      - name: e2thstream
        image: aelmendorf234/monitoringdatadataloggingservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DEVICEID
          value: e2th
        - name: SERVICE_TYPE
          value: GenericModbus
  selector:
    matchLabels:
      app: e2thstream
---
apiVersion: v1
kind: Service
metadata:
  name: e2thstream
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: e2thstream