apiVersion: apps/v1
kind: Deployment
metadata:
  name: epijobserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: epijobserver
    spec:
      containers:
      - name: epijobserver
        image: aelmendorf234/epijobsserver:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: epijobserver
---
apiVersion: v1
kind: Service
metadata:
  name: epijobserver
spec:
  loadBalancerIP: 172.20.4.205
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: epijobserver