apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-ns
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          imagePullPolicy: Always
          args: ["start","--features=scripts","--http-enabled=true", "--hostname-strict=false"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KC_DB_SCHEMA
              value: "keycloak"
            - name: KC_HTTP_ENABLED
              value: "true"
            # External Postgres Configuration
            - name: KC_DB
              value: postgres
          envFrom:
          - configMapRef:
              name: keycloak-config-map
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1700Mi
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak-ns
spec:
  loadBalancerIP: 172.20.4.212
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: keycloak