apiVersion: v1
kind: Secret
metadata:
  name: developer-user-credentials
  namespace: epi-system
type: Opaque
stringData:
  username: developer_user
  password: "C94ED0DA1A7E4B77BCFC31D0D2B2FB48"
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-admin-credentials
  namespace: epi-system
type: Opaque
stringData:
  username: cluster_admin
  password: "ABBDEB5F2F25CCC62C4B916BD99215E5"